import { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: "p1",
    slug: "aether-pendant",
    name: "Aether Kolye Ucu",
    category: "Kolye",
    description:
      "Yüksek polisaj pirinç gövde, akıcı geometrik form ve keskin alt bitiş ile premium kolye tasarımı.",
    price: 3250,
    material: "Masif pirinç, elde parlatılmış",
    image: "/products/aether.jpg",
    collection: "Atelier 01",
    finish: "Ayna polisaj",
    stock: 14,
    leadTimeDays: 4,
    tags: ["Geometrik", "Statement", "Yeni Sezon"],
    isNew: true,
  },
  {
    id: "p2",
    slug: "linea-bracelet",
    name: "Linea Bileklik",
    category: "Bileklik",
    description:
      "Minimal çizgi formu ve sıcak altın tonuyla günlük kullanımda lüks bir ifade sunar.",
    price: 2550,
    material: "Masif pirinç",
    image: "/products/linea.jpg",
    collection: "Atelier 01",
    finish: "Saten + parlak geçiş",
    stock: 18,
    leadTimeDays: 3,
    tags: ["Minimal", "Günlük", "Unisex"],
  },
  {
    id: "p3",
    slug: "monolith-pin",
    name: "Monolith Pin",
    category: "Pin",
    description:
      "Keskin hatlara sahip modern pirinç pin; ceket ve çanta kombinlerinde güçlü vurgu.",
    price: 1450,
    material: "Masif pirinç",
    image: "/products/monolith.jpg",
    collection: "Monolith",
    finish: "Parlak yüzey",
    stock: 12,
    leadTimeDays: 2,
    tags: ["Keskin Hat", "Şehir", "Unisex"],
  },
  {
    id: "p4",
    slug: "arc-earring",
    name: "Arc Küpe",
    category: "Küpe",
    description:
      "Hafif kavisli form, parlak yüzey ve konforlu kilit mekanizması ile modern küpe.",
    price: 1980,
    material: "Masif pirinç",
    image: "/products/arc.jpg",
    collection: "Arc Form",
    finish: "Ayna polisaj",
    stock: 10,
    leadTimeDays: 3,
    tags: ["Hafif", "Modern", "Günlük"],
    isNew: true,
  },
  {
    id: "p5",
    slug: "forge-keychain",
    name: "Forge Anahtarlık",
    category: "Anahtarlık",
    description:
      "Mimari formlu premium anahtarlık; dayanıklı, ağırlık hissi veren artisanal dokunuş.",
    price: 1680,
    material: "Masif pirinç",
    image: "/products/forge.jpg",
    collection: "Forge",
    finish: "Fırçalı + parlak kenar",
    stock: 20,
    leadTimeDays: 2,
    tags: ["Aksesuar", "Dayanıklı", "Hediye"],
  },
  {
    id: "p6",
    slug: "nova-pendant",
    name: "Nova Kolye Ucu",
    category: "Kolye",
    description:
      "Katmanlı kırık yüzeyleriyle ışığı farklı açılarda yakalayan iddialı bir kolye tasarımı.",
    price: 3590,
    material: "Masif pirinç, elde parlatılmış",
    image: "/products/nova.jpg",
    collection: "Nova Lab",
    finish: "Yüksek parlaklık",
    stock: 6,
    leadTimeDays: 5,
    tags: ["Yeni Sezon", "Heykelsi", "Özel Üretim"],
    isNew: true,
    isLimited: true,
  },
  {
    id: "p7",
    slug: "rivet-bracelet",
    name: "Rivet Bileklik",
    category: "Bileklik",
    description:
      "Mimari vidalama detaylarından ilham alan güçlü form; tek başına dahi etkileyici görünüm.",
    price: 2890,
    material: "Masif pirinç",
    image: "/products/rivet.jpg",
    collection: "Forge",
    finish: "Saten yüzey",
    stock: 9,
    leadTimeDays: 4,
    tags: ["Endüstriyel", "Güçlü Silüet", "Unisex"],
  },
  {
    id: "p8",
    slug: "halo-earring",
    name: "Halo Küpe",
    category: "Küpe",
    description:
      "İnce halka ve keskin geçişlerin dengesiyle modern, sade ve premium bir kulak formu.",
    price: 2140,
    material: "Masif pirinç",
    image: "/products/halo.jpg",
    collection: "Arc Form",
    finish: "Parlak yüzey",
    stock: 13,
    leadTimeDays: 3,
    tags: ["Minimal", "Hafif", "Yeni Sezon"],
  },
  {
    id: "p9",
    slug: "axis-pin",
    name: "Axis Pin",
    category: "Pin",
    description:
      "Açılı yüzeyleri ve tek parça görünümüyle blazer, gömlek ve çantalarda güçlü bir vurgu sağlar.",
    price: 1590,
    material: "Masif pirinç",
    image: "/products/axis.jpg",
    collection: "Monolith",
    finish: "Ayna polisaj",
    stock: 7,
    leadTimeDays: 2,
    tags: ["Keskin Hat", "Hediye", "Limited"],
    isLimited: true,
  },
  {
    id: "p10",
    slug: "pin-rozet-atelier",
    name: "Pin Rozet Atelier",
    category: "Pin",
    description:
      "Atölye üretimi pirinç rozet pin; ceket, çanta ve gömlekte mimari bir vurgu oluşturur.",
    price: 1750,
    material: "Masif pirinç",
    image: "/products/monolith.jpg",
    collection: "Atelier Rozet",
    finish: "Ayna polisaj",
    stock: 25,
    leadTimeDays: 2,
    tags: ["Pin", "Rozet", "Atölye", "Yeni"],
    isNew: true,
  },
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}
